update 0-custom_http_response_header and 1-install_load_balancer files

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,80 +1,84 @@
 #!/usr/bin/env bash
-# Configure Nginx so that it's HTTP response contains a custome header (on web-01 and web-02)
-# The name of the custom HTTP header must be X-Served-By
-# The value of the custom HTTP header must be the hostname of the server Nginx is running on
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
-sudo apt-get update -y
-sudo apt-get install nginx -y
-# Update the package list and install Nginx using `apt-get`.
-# The `-y` flag is used to automatically answer
-# "yes" to any prompts during the installation process.
+# uncomment to see the script run in action
+#set -x
 
+echo -e "Updating and doing some minor checks...\n"
+
+function install() {
+	command -v "$1" &> /dev/null
+
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
+
+install nginx #install nginx
+
+echo -e "\nSetting up some minor stuff.\n"
+
+# allowing nginx on firewall
 sudo ufw allow 'Nginx HTTP'
-# Allow incoming HTTP traffic through the UFW firewall.
-# This line opens port 80, which is the default port for HTTP traffic.
 
-# change permissions to allow us to easily create files in this directory
-sudo chmod -R 755 /var/www
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
 
-#echo "Hello World!" > /var/www/html/index.nginx-debian.html
-echo "Hello World!" | sudo tee /var/www/html/index.html
-# Create an `index.nginx-debian.html` file in the `/var/www/html` directory
-# and write the text "Hello World!" into it.
-# This file will be served as the default landing page by Nginx.
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
 
-#echo "Ceci n'est pas une error_page" > /usr/share/nginx/html/custom_404.html
-# Create a `custom_404.html` file in the `/usr/share/nginx/html` directory
-echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
-# Create a `custom_404.html` file in the `/var/www/html` directory
-# and write the text "Ceci n'est pas une error_page" into it.
-# This file will be used as a custom 404 error page.
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
 
-server_name=$(hostname)
-# Allow incoming HTTP traffic through the UFW firewall.
-# This line opens port 80, which is the default port for HTTP traffic.
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
 
-SERVER_CONFIG=\
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+server_config=\
 "server {
-    listen 80 default_server;
-    listen [::]:80 default_server;
-
-    root /var/www/html;
-
-    # Add index.php to the list if you are using PHP
-    index index.html index.htm index.nginx-debian.html;
-
-    server_name _;
-
-    location / {
-        # First attempt to serve request as file, then
-        # as a directory, then fall back to displaying a 404.
-        try_files \$uri \$uri/ =404;
-    }
-
-    error_page 404 /custom_404.html;
-    location = /custom_404.html {
-        root /var/www/html;
-        internal;
-    }
-
-    location /redirect_me {
-        return 301 https://www.youtube.com/watch?v=3lFkDc6dFoY;
-    }
-
-    add_header X-Served-By $server_name;
-
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
 }"
-#> /etc/nginx/sites-enabled/default
-bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"
-# Write the Nginx server configuration to
-# the `/etc/nginx/sites-enabled/default` file.
-# This configuration sets Nginx to listen on port 80,
-# sets the root directory to `/var/www/html`,
-# defines the default index files, specifies a
-# location block for handling requests,
-# sets a custom 404 error page, defines a location
-# block for redirecting requests to `/redirect_me`, and adds an
-# `X-Served-By` header with the value of the `server_name` variable.
 
-sudo service nginx restart
-# Restart the Nginx service to apply the new configuration.
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
